### ISSUE TITLE
config/connections.js configures default invalid connections for new projects

### ISSUE THREAD

**Issue by animedbz16** [balderdashy/sails-generate-backend#31]
Within `templates/config/connections.js`, this file actually defines default connections.

https://github.com/balderdashy/sails-generate-backend/blob/v0.12.4/templates/config/connections.js

These should be commented out by default, especially since most of them require additional npm packages to be installed.

After creating a new project and defining our mongo configuration into `config/env/development.js`, we kept seeing issues where on `sails lift` it was attempting to access a mongo server on localhost. 

I assume that since these connections are defined here and even though we were not actually using them, on sails lift, it attempts to connect to these.

I would recommend that they be commented out by default and possibly leaving just sails-disk uncommented since this is the default on a new install anyways.

**Comment by robgrimball** [comment]
:+1:

**Comment by sgress454** [comment]
@animedbz16 @robgrimball Thanks for the post and sorry for the confusion this has caused!  

This is a symptom of the behavior documented in the note [here](http://sailsjs.org/documentation/reference/configuration/sails-config-connections#?multiple-connections-for-an-adapter), but rather more probably a symptom of our (or at least my) lazy habit of renaming and reusing the connections from that default config file, so that we don't end up seeing what is rather an obvious problem, with a fairly obvious solution to boot.  Looking at the PR now.
